### ISSUE TITLE
Documentation for Setting Up Deployment

### ISSUE THREAD

**Issue by sderacy** [tcnj-acm/halo#123]
## A clear and concise description of what the problem is.

There are a couple of issues that newer people might run into when picking up this project, so there should be documentation on operations such as deploying locally vs deploying to Heroku.

## A clear and concise description of what you want to happen.

More documentation regarding:

- Deploying code to Heroku
- Deploying code locally
- Creating superuser and or setting up env files

### Additional context

Add any other context such as screenshots, schematics, about the feature request here.

**Comment by Simon-Blamo** [comment]
I'll take a look at this.

**Comment by Simon-Blamo** [comment]
Resolved this issue.
