### ISSUE TITLE
Color Code Food Preference

### ISSUE THREAD

**Issue by sderacy** [tcnj-acm/halo#136]
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is.

# Trying to tell what band a hacker needs is inefficient because when a lot of hackers are checking in at once, you need to quickly read who has what preference so you can keep the check-in line moving.

### Describe the solution you'd like

# It would be easier for check-in and stats if the tuples were color-coded. For example, if the person checking in sees a blue highlight over the text for "None", then they do not have to actually read it and they can just instinctively know what band they should get.

**Comment by Simon-Blamo** [comment]
Will take a look at this.

**Comment by Simon-Blamo** [comment]
Added feature.

**Comment by sderacy** [comment]
Nice work! Can you post a link to the change when you close these out? @Simon-Blamo
