### ISSUE TITLE
Change Birth Date Field to Age

### ISSUE THREAD

**Issue by sderacy** [tcnj-acm/halo#138]
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is.

# Users have to put in their birth date to have their age calculated.

### Describe the solution you'd like

# Switch this field to just be an "age" field so users can enter their age as a numeric value.

**Comment by Negarbsh** [comment]
I would like to fix it if possible.

**Comment by Negarbsh** [comment]
I can fix this if it's ok.

**Comment by sderacy** [comment]
I'm no longer responsible for this repository but if you make a pull request I can ensure that those who are will at least review it.

**Comment by Simon-Blamo** [comment]
I think the better solution is to derive the age from the birth date entered by user. This way the ages are up-to-date within the database as the year progress.

Will take a look into this.

**Comment by Simon-Blamo** [comment]
I added a "dob" column, to the custom user table. Now the ages of users can be derived from this column, and the age column can be up-to-date in the DB.
